#!/bin/bash
echo ""
echo "Self Extracting Installer"
echo ""

if [[ $# -ne 1 ]]; then
	echo "Usage: $0 <install | cleanup>"
	exit 1 
fi

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root"
	exit 1
fi

export TMPDIR=`mktemp -d /tmp/selfextract.XXXXXX`

ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`

tail -n+$ARCHIVE $0 | tar xzv -C $TMPDIR

CDIR=`pwd`
cd $TMPDIR/biosfix

if [[ $1 == "cleanup" ]]; then
	./biosfix.sh cleanup
else
	./biosfix.sh biosfix_data.tar.gz
fi

cd $CDIR
rm -rf $TMPDIR

exit 0
__ARCHIVE_BELOW__
